enhanced acceptance tests scripts

diff --git a/acceptance/dpp/run/chimera-all b/acceptance/dpp/run/chimera-all
--- a/acceptance/dpp/run/chimera-all
+++ b/acceptance/dpp/run/chimera-all
@@ -1,5 +1,26 @@
 #!/usr/bin/env bash
-#./chimera23-default $1/Chimera23_FTR_C_EN_XG-NR_20_4K_20150603_OV $2;
-./chimera25-default $1/Chimera25_FTR_C_EN_XG-NR_20_4K_20150608_OV $2;
-#./chimera29-default $1/Chimera29_FTR_C_EN_XG-NR_20_4K_20150624_OV $2;
-./chimera50-default $1/Chimera50_FTR_C_EN_XG-NR_20_4K_20150622_OV $2
+
+function usage {
+    echo "Convert all default test packages to DPP Format."
+    echo "1st argument - a path to the directory containing all default test packages."
+    echo "2d argument - a path to the directory containing the output for all test packages."
+    echo "3d argument - a path to imf-conversion-utility (if not set a default one will be used assuming that we're in the source root folder)."
+}
+
+if [ -z "$1" ]; then
+    echo "Missing argument: a path to the directory containing all default test packages."
+    usage
+    exit 1
+fi
+
+if [ -z "$2" ]; then
+    echo "Missing argument: a path to the directory containing the output for all test packages."
+    usage
+    exit 1
+fi
+
+#./chimera23-default "$1/Chimera23_FTR_C_EN_XG-NR_20_4K_20150603_OV" "$2" "$3";
+#./chimera25-default "$1/Chimera25_FTR_C_EN_XG-NR_20_4K_20150608_OV" "$2" "$3";
+#./chimera50-default "$1/Chimera50_FTR_C_EN_XG-NR_20_4K_20150622_OV" "$2" "$3";
+#./chimera29-default "$1/Chimera29_FTR_C_EN_XG-NR_20_4K_20150624_OV" "$2" "$3";
+./chimera25-short "$1/Chimera25_FTR_C_EN_XG-NR_20_4K_20150608_OV" "$2" "$3";
diff --git a/acceptance/dpp/run/dpp b/acceptance/dpp/run/dpp
--- a/acceptance/dpp/run/dpp
+++ b/acceptance/dpp/run/dpp
@@ -1,2 +1,42 @@
 #!/usr/bin/env bash
-../../../install/imf-conversion-utility/bin/imf-conversion-utility -f dpp -c ../../config.xml -m convert --imp $1 --cpl $2 -w $3 --metadata $4
+
+function usage {
+    echo "Converts to DPP format"
+    echo "1st argument - a path to IMP directory."
+    echo "2d argument - a path to CPL."
+    echo "3d argument - a path to the directory containing the output for the test packages."
+    echo "4th argument - a path to metadata.xml."
+    echo "5th argument - a path to imf-conversion-utility (if not set a default one will be used assuming that we're in the source root folder)."
+}
+
+
+if [ -z "$1" ]; then
+    echo "Missing argument: a path to IMP directory."
+    usage
+    exit 1
+fi
+
+if [ -z "$2" ]; then
+    echo "Missing argument: a path to CPL."
+    usage
+    exit 1
+fi
+
+if [ -z "$3" ]; then
+    echo "Missing argument: a path to the directory containing the output for the test packages."
+    usage
+    exit 1
+fi
+
+if [ -z "$4" ]; then
+    echo "Missing argument: a path to metadata.xml."
+    usage
+    exit 1
+fi
+
+PROG="$5"
+if [ -z "$5" ]; then
+    PROG="../../../install/imf-conversion-utility/bin/imf-conversion-utility"
+fi
+
+"$PROG" -f dpp -c "../../config.xml" -m convert --imp "$1" --cpl "$2" -w "$3" --metadata "$4"
