add acceptance tests for audiomap.

diff --git a/acceptance/dpp/run/dpp-audiomap b/acceptance/dpp/run/dpp-audiomap
--- a/acceptance/dpp/run/dpp-audiomap
+++ b/acceptance/dpp/run/dpp-audiomap
@@ -7,7 +7,8 @@ function usage {
     echo "3d argument - a path to the directory containing the output for the test packages."
     echo "4th argument - a path to metadata.xml."
     echo "5th argument - a path to the output .mxf name (without .mxf extension)."
-    echo "6th argument - a path to imf-conversion-utility (if not set a default one will be used assuming that we're in the source root folder)."
+    echo "6th argument - a path to audiomap.xml."
+    echo "7th argument - a path to imf-conversion-utility (if not set a default one will be used assuming that we're in the source root folder)."
 }
 
 
@@ -41,10 +42,16 @@ if [ -z "$5" ]; then
     exit 1
 fi
 
-cd "${BASH_SOURCE%/*}"
-PROG="$6"
 if [ -z "$6" ]; then
+    echo "Missing argument: a path to audiomap.xml."
+    usage
+    exit 1
+fi
+
+cd "${BASH_SOURCE%/*}"
+PROG="$7"
+if [ -z "$7" ]; then
     PROG="../../../install/imf-conversion-utility/bin/imf-conversion-utility"
 fi
 
-"$PROG" dpp -c "../../config.xml" -m convert --imp "$1" --cpl "$2" -w "$3" --metadata "$4" -o "$5"
+"$PROG" dpp -c "../../config.xml" -m convert --imp "$1" --cpl "$2" -w "$3" --metadata "$4" -o "$5" --audiomap "$6"
